# Generated by Django 3.0.7 on 2020-07-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='updated_on',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='book',
            name='user_updated',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
