# Generated by Django 3.0.7 on 2020-07-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200720_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='user_updated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
