# Generated by Django 3.0.7 on 2020-07-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200720_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='user_updated',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
