# Generated by Django 3.0.7 on 2020-07-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200720_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='user_updated',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
