# Generated by Django 3.0.7 on 2020-07-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200720_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='created_by',
        ),
    ]
