# Generated by Django 3.0.7 on 2020-07-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200720_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_by',
            new_name='user',
        ),
    ]
