# Generated by Django 3.0.7 on 2020-07-29 06:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200721_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.book_pdf_file_path),
        ),
    ]
